import { InteractionEventEntity } from '../entities/interaction-event.entity';
import { InteractionStreamEntity, InteractionContextType } from '../entities/interaction-stream.entity';

/**
 * AI Action Types
 * 
 * Defines what the AI can do in response to interaction events
 */
export enum AIActionType {
  RESPOND = 'RESPOND',
  SUMMARIZE = 'SUMMARIZE',
  ESCALATE = 'ESCALATE',
  TRIGGER_WORKFLOW = 'TRIGGER_WORKFLOW',
  ASK_CLARIFICATION = 'ASK_CLARIFICATION',
  BLOCK_MESSAGE = 'BLOCK_MESSAGE',
  DETECT_INTENT = 'DETECT_INTENT',
  ANALYZE_SENTIMENT = 'ANALYZE_SENTIMENT',
  SUGGEST_RESPONSE = 'SUGGEST_RESPONSE',
}

/**
 * Intent Types
 * 
 * Common intents that can be detected from user messages
 */
export enum IntentType {
  CREATE_ORDER = 'CREATE_ORDER',
  CHECK_STATUS = 'CHECK_STATUS',
  CANCEL_ORDER = 'CANCEL_ORDER',
  MODIFY_ORDER = 'MODIFY_ORDER',
  MAKE_PAYMENT = 'MAKE_PAYMENT',
  GET_SUPPORT = 'GET_SUPPORT',
  GET_ESTIMATE = 'GET_ESTIMATE',
  SCHEDULE_PICKUP = 'SCHEDULE_PICKUP',
  ASK_QUESTION = 'ASK_QUESTION',
  GIVE_FEEDBACK = 'GIVE_FEEDBACK',
  UNKNOWN = 'UNKNOWN',
}

/**
 * Sentiment Types
 */
export enum SentimentType {
  POSITIVE = 'POSITIVE',
  NEGATIVE = 'NEGATIVE',
  NEUTRAL = 'NEUTRAL',
  FRUSTRATED = 'FRUSTRATED',
  SATISFIED = 'SATISFIED',
}

/**
 * Reasoning Step
 * 
 * Represents a single step in the AI's reasoning process
 */
export interface ReasoningStep {
  step: string;
  reasoning: string;
  confidence: number;
  timestamp: Date;
}

/**
 * Intent Detection Result
 */
export interface IntentDetectionResult {
  intent: IntentType;
  entities: Record<string, string>;
  confidence: number;
  reasoning: ReasoningStep[];
}

/**
 * Sentiment Analysis Result
 */
export interface SentimentAnalysisResult {
  sentiment: SentimentType;
  confidence: number;
  reasoning: ReasoningStep[];
}

/**
 * AI Response
 * 
 * Represents a response generated by the AI
 */
export interface AIResponse {
  message: string;
  action: AIActionType;
  confidence: number;
  suggestedActions?: string[];
  metadata?: Record<string, unknown>;
}

/**
 * AI Recommendation
 * 
 * Full recommendation from the intelligence engine
 */
export interface AIRecommendation {
  action: AIActionType;
  response?: AIResponse;
  intentDetected?: IntentDetectionResult;
  sentimentAnalysis?: SentimentAnalysisResult;
  shouldEscalate: boolean;
  shouldTriggerWorkflow: boolean;
  workflowType?: string;
  workflowPayload?: Record<string, unknown>;
  reasoning: ReasoningStep[];
  confidenceScore: number;
}

/**
 * Interaction Intelligence Context
 * 
 * Contextual information for AI reasoning about interactions
 */
export interface InteractionIntelligenceContext {
  // Stream information
  stream: InteractionStreamEntity;
  
  // Recent events in the stream (last N events)
  recentEvents: InteractionEventEntity[];
  
  // All participants in the stream
  participantIds: string[];
  
  // Context type and ID (e.g., ORDER, orderId)
  contextType: InteractionContextType;
  contextId: string;
  
  // Current event being processed
  currentEvent?: InteractionEventEntity;
  
  // Historical summary if available
  summary?: string;
  
  // Metadata from the stream
  metadata?: Record<string, unknown>;
  
  // Requested action type (if any)
  requestedAction?: AIActionType;
  
  // Timestamp for when context was built
  builtAt: Date;
}

/**
 * Interaction Intelligence Configuration
 */
export interface InteractionIntelligenceConfig {
  // Enable/disable specific features
  enableIntentDetection: boolean;
  enableSentimentAnalysis: boolean;
  enableSummarization: boolean;
  enableEscalationDetection: boolean;
  
  // Thresholds
  minConfidenceThreshold: number;
  sentimentThreshold: number;
  
  // Limits
  maxRecentEvents: number;
  maxSummaryLength: number;
  
  // Response settings
  defaultLanguage: string;
  enableSuggestedActions: boolean;
}

/**
 * Default configuration
 */
export const DEFAULT_INTELLIGENCE_CONFIG: InteractionIntelligenceConfig = {
  enableIntentDetection: true,
  enableSentimentAnalysis: true,
  enableSummarization: true,
  enableEscalationDetection: true,
  minConfidenceThreshold: 0.7,
  sentimentThreshold: 0.6,
  maxRecentEvents: 10,
  maxSummaryLength: 500,
  defaultLanguage: 'en',
  enableSuggestedActions: true,
};
