/**
 * SDUIRenderer Integration Tests
 * 
 * Tests the SDUI renderer component - passing schemas directly
 * to test rendering behavior without network dependencies.
 * 
 * Run with: npm test -- --testPathPattern="SDUIRenderer"
 */

import React from 'react';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { SDUIRenderer } from '../SDUIRenderer';
import type { UISchema } from '../../../types/sdui.types';

// Mock screen schemas for testing - these use the component's expected schema format
const mockLoginSchema = {
  id: 'login',
  version: '1.0.0',
  metadata: {
    title: 'Test Login',
    description: 'Login screen for testing',
    type: 'login' as const,
    auth: 'none' as const,
  },
  layout: {
    type: 'stack' as const,
    props: { maxWidth: 400, spacing: 2 },
    components: [
      {
        component: 'Typography',
        id: 'title',
        props: { variant: 'h5', align: 'center', content: 'Welcome Back' },
      },
      {
        component: 'TextField',
        id: 'email',
        props: { 
          name: 'email', 
          label: 'Email', 
          type: 'email', 
          fullWidth: true, 
          required: true 
        },
      },
      {
        component: 'TextField',
        id: 'password',
        props: { 
          name: 'password', 
          label: 'Password', 
          type: 'password', 
          fullWidth: true, 
          required: true 
        },
      },
      {
        component: 'Button',
        id: 'submit',
        props: { 
          variant: 'contained', 
          fullWidth: true, 
          type: 'submit', 
          content: 'Sign In' 
        },
      },
    ],
  },
  validations: [
    { field: 'email', type: 'required' as const, message: 'Email is required' },
    { field: 'email', type: 'email' as const, message: 'Invalid email format' },
    { field: 'password', type: 'required' as const, message: 'Password is required' },
  ],
  actions: [
    { id: 'submit', type: 'submit' as const, label: 'Sign In', endpoint: '/api/auth/login', method: 'POST' },
  ],
} as unknown as UISchema;

// Movers Homepage Schema - matches the schema generated by the API
const mockMoversHomeSchema = {
  screenId: 'movers-home',
  version: '1.0.0',
  metadata: {
    title: 'ZanaFleet Movers',
    description: 'Professional moving and transportation services',
    type: 'movers-home' as const,
    auth: 'none' as const,
    cacheDuration: 300,
    offlineCapable: false,
  },
  data: [
    {
      id: 'config',
      type: 'static' as const,
      endpoint: '/api/sdui/screens/movers-home/config',
      staticData: {
        companyName: 'ZanaFleet Movers',
        tagline: 'Reliable Moving Services',
        ctaText: 'Get a Free Quote',
        phoneNumber: '+254 700 000 000',
        email: 'info@zanafleet.movers',
      },
      cacheable: true,
      cacheDuration: 3600,
    },
  ],
  layout: {
    type: 'flex' as const,
    props: {
      direction: 'column',
      spacing: 0,
    },
    children: [
      // Hero Section
      {
        type: 'flex' as const,
        props: {
          direction: 'column',
          align: 'center',
          justify: 'center',
          padding: 6,
          backgroundColor: '#1E3A5F',
        },
        components: [
          {
            component: 'Typography',
            props: {
              variant: 'h2',
              color: '#FFFFFF',
              align: 'center',
              content: '{{config.companyName}}',
            },
          },
          {
            component: 'Typography',
            props: {
              variant: 'h5',
              color: '#B0C4DE',
              align: 'center',
              content: '{{config.tagline}}',
            },
          },
          {
            component: 'Button',
            props: {
              variant: 'contained',
              color: 'primary',
              size: 'large',
              content: '{{config.ctaText}}',
            },
          },
        ],
      },
      // Services Section
      {
        type: 'stack' as const,
        props: {
          spacing: 4,
          padding: 6,
        },
        components: [
          {
            component: 'Typography',
            props: {
              variant: 'h4',
              align: 'center',
              content: 'Our Services',
            },
          },
          {
            component: 'Card',
            props: {
              title: 'Residential Moving',
              content: 'Safe and secure home relocation',
            },
          },
          {
            component: 'Card',
            props: {
              title: 'Commercial Moving',
              content: 'Office and business relocation',
            },
          },
          {
            component: 'Card',
            props: {
              title: 'Packing Services',
              content: 'Professional packing and unpacking',
            },
          },
          {
            component: 'Card',
            props: {
              title: 'Storage Solutions',
              content: 'Secure storage facilities',
            },
          },
        ],
      },
      // CTA Section
      {
        type: 'flex' as const,
        props: {
          direction: 'column',
          align: 'center',
          padding: 6,
          spacing: 3,
        },
        components: [
          {
            component: 'Typography',
            props: {
              variant: 'h4',
              align: 'center',
              content: 'Ready to Move?',
            },
          },
          {
            component: 'Typography',
            props: {
              variant: 'body1',
              align: 'center',
              content: 'Contact us for a free quote today',
            },
          },
          {
            component: 'Button',
            props: {
              variant: 'contained',
              color: 'primary',
              size: 'large',
              content: '{{config.ctaText}}',
            },
          },
          {
            component: 'Typography',
            props: {
              variant: 'body2',
              align: 'center',
              content: 'Phone: {{config.phoneNumber}}',
            },
          },
          {
            component: 'Typography',
            props: {
              variant: 'body2',
              align: 'center',
              content: 'Email: {{config.email}}',
            },
          },
        ],
      },
    ],
  },
  actions: [
    {
      id: 'open-quote-form',
      type: 'navigate' as const,
      label: 'Get Quote',
      navigateTo: 'quote',
    },
    {
      id: 'navigate-to-login',
      type: 'navigate' as const,
      label: 'Login',
      navigateTo: 'login',
    },
  ],
} as unknown as UISchema;

const mockDashboardSchema = {
  id: 'dashboard.admin',
  version: '1.0.0',
  metadata: {
    title: 'Admin Dashboard',
    description: 'System overview',
    type: 'dashboard' as const,
    auth: 'required' as const,
  },
  layout: {
    type: 'root' as const,
    components: [
      {
        component: 'Typography',
        id: 'welcome',
        props: { variant: 'h4', content: 'Welcome, Administrator' },
      },
    ],
    children: [
      {
        type: 'grid' as const,
        props: { spacing: 3 },
        children: [
          {
            type: 'stack' as const,
            props: { spacing: 2 },
            components: [
              {
                component: 'MetricCard',
                id: 'total-users',
                props: { label: 'Total Users', value: '1,234', trend: 'up', change: '+12%' },
              },
            ],
          },
          {
            type: 'stack' as const,
            props: { spacing: 2 },
            components: [
              {
                component: 'MetricCard',
                id: 'active-rides',
                props: { label: 'Active Rides', value: '89', trend: 'down', change: '-5%' },
              },
            ],
          },
        ],
      },
    ],
  },
  actions: [
    { id: 'refresh', type: 'api' as const, label: 'Refresh Data', endpoint: '/api/dashboard/refresh', method: 'POST' },
  ],
} as unknown as UISchema;

const mockDataTableSchema = {
  id: 'deliveries',
  version: '1.0.0',
  metadata: {
    title: 'Deliveries',
    description: 'Recent delivery orders',
    type: 'list' as const,
    auth: 'required' as const,
  },
  layout: {
    type: 'stack' as const,
    props: { spacing: 2 },
    components: [
      {
        component: 'Typography',
        id: 'table-title',
        props: { variant: 'h6', content: 'Recent Deliveries' },
      },
      {
        component: 'DataTable',
        id: 'deliveries-table',
        props: {
          columns: [
            { key: 'id', label: 'Order ID' },
            { key: 'customer', label: 'Customer' },
            { key: 'status', label: 'Status' },
            { key: 'amount', label: 'Amount (KES)' },
          ],
          rows: [
            { id: 'ORD-001', customer: 'John Doe', status: 'Delivered', amount: '1,500' },
            { id: 'ORD-002', customer: 'Jane Smith', status: 'In Transit', amount: '2,300' },
            { id: 'ORD-003', customer: 'Bob Wilson', status: 'Pending', amount: '890' },
          ],
        },
      },
    ],
  },
  actions: [],
} as unknown as UISchema;

const mockCardSchema = {
  id: 'card-test',
  version: '1.0.0',
  metadata: { 
    title: 'Card Test',
    type: 'detail' as const,
    auth: 'none' as const,
  },
  layout: {
    type: 'stack' as const,
    props: { spacing: 2 },
    components: [
      {
        component: 'Card',
        id: 'test-card',
        props: { 
          title: 'Test Card Title',
          content: 'This is the card content text.',
        },
      },
      {
        component: 'Chip',
        id: 'status-chip',
        props: { label: 'Active', color: 'success' },
      },
      {
        component: 'Chip',
        id: 'warning-chip',
        props: { label: 'Warning', color: 'warning' },
      },
      {
        component: 'Chip',
        id: 'error-chip',
        props: { label: 'Error', color: 'error' },
      },
    ],
  },
  actions: [],
} as unknown as UISchema;

describe('SDUIRenderer Integration Tests', () => {
  describe('Login Screen Rendering', () => {
    it('renders login form with all fields', () => {
      render(<SDUIRenderer schema={mockLoginSchema} screenId="login" />);
      
      // Check title is rendered
      expect(screen.getByText('Test Login')).toBeInTheDocument();
      expect(screen.getByText('Login screen for testing')).toBeInTheDocument();
      
      // Check form fields
      expect(screen.getByLabelText(/email/i)).toBeInTheDocument();
      expect(screen.getByLabelText(/password/i)).toBeInTheDocument();
      
      // Check submit button
      expect(screen.getByRole('button', { name: /sign in/i })).toBeInTheDocument();
    });

    it('shows validation errors on empty submit', async () => {
      const user = userEvent.setup();
      render(<SDUIRenderer schema={mockLoginSchema} screenId="login" />);
      
      // Click submit without entering data
      await user.click(screen.getByRole('button', { name: /sign in/i }));
      
      // Check validation errors appear
      await waitFor(() => {
        const errorMessages = screen.getAllByRole('alert');
        expect(errorMessages.length).toBeGreaterThan(0);
      });
    });
  });

  describe('Dashboard Rendering', () => {
    it('renders dashboard with metric cards', () => {
      render(<SDUIRenderer schema={mockDashboardSchema} screenId="dashboard.admin" />);
      
      // Check title
      expect(screen.getByText('Admin Dashboard')).toBeInTheDocument();
      expect(screen.getByText('System overview')).toBeInTheDocument();
      
      // Check metric cards
      expect(screen.getByText('Total Users')).toBeInTheDocument();
      expect(screen.getByText('1,234')).toBeInTheDocument();
      expect(screen.getByText('+12%')).toBeInTheDocument();
      
      expect(screen.getByText('Active Rides')).toBeInTheDocument();
      expect(screen.getByText('89')).toBeInTheDocument();
    });

    it('renders action buttons', () => {
      render(<SDUIRenderer schema={mockDashboardSchema} screenId="dashboard.admin" />);
      
      expect(screen.getByRole('button', { name: /refresh data/i })).toBeInTheDocument();
    });

    it('displays welcome message', () => {
      render(<SDUIRenderer schema={mockDashboardSchema} screenId="dashboard.admin" />);
      
      expect(screen.getByText('Welcome, Administrator')).toBeInTheDocument();
    });
  });

  describe('DataTable Rendering', () => {
    it('renders data table with correct columns and rows', () => {
      render(<SDUIRenderer schema={mockDataTableSchema} screenId="deliveries" />);
      
      // Check title
      expect(screen.getByText('Recent Deliveries')).toBeInTheDocument();
      
      // Check table headers
      expect(screen.getByText('Order ID')).toBeInTheDocument();
      expect(screen.getByText('Customer')).toBeInTheDocument();
      expect(screen.getByText('Status')).toBeInTheDocument();
      expect(screen.getByText('Amount (KES)')).toBeInTheDocument();
      
      // Check table rows
      expect(screen.getByText('ORD-001')).toBeInTheDocument();
      expect(screen.getByText('John Doe')).toBeInTheDocument();
      expect(screen.getByText('Delivered')).toBeInTheDocument();
      expect(screen.getByText('1,500')).toBeInTheDocument();
    });

    it('renders all rows correctly', () => {
      render(<SDUIRenderer schema={mockDataTableSchema} screenId="deliveries" />);
      
      // All customers should be present
      expect(screen.getByText('Jane Smith')).toBeInTheDocument();
      expect(screen.getByText('Bob Wilson')).toBeInTheDocument();
      
      // All statuses
      expect(screen.getByText('In Transit')).toBeInTheDocument();
      expect(screen.getByText('Pending')).toBeInTheDocument();
    });
  });

  describe('Card and Chip Components', () => {
    it('renders card with title and content', () => {
      render(<SDUIRenderer schema={mockCardSchema} screenId="card-test" />);
      
      expect(screen.getByText('Test Card Title')).toBeInTheDocument();
      expect(screen.getByText('This is the card content text.')).toBeInTheDocument();
    });

    it('renders chips with correct labels', () => {
      render(<SDUIRenderer schema={mockCardSchema} screenId="card-test" />);
      
      expect(screen.getByText('Active')).toBeInTheDocument();
      expect(screen.getByText('Warning')).toBeInTheDocument();
      expect(screen.getByText('Error')).toBeInTheDocument();
    });
  });

  describe('Navigation Actions', () => {
    it('calls onNavigate for navigation actions', async () => {
      const onNavigate = jest.fn();
      const navigateSchema = {
        id: 'nav-test',
        version: '1.0.0',
        metadata: { 
          title: 'Navigation Test',
          type: 'form' as const,
          auth: 'none' as const,
        },
        layout: {
          type: 'stack' as const,
          components: [
            {
              component: 'Button',
              id: 'nav-button',
              props: { content: 'Navigate Button' },
            },
          ],
        },
        // No global actions - navigation comes from component action
        actions: [
          { id: 'nav-button', type: 'navigate' as const, label: 'Navigate Button', navigateTo: '/dashboard' },
        ],
      } as unknown as UISchema;
      
      const user = userEvent.setup();
      render(
        <SDUIRenderer 
          schema={navigateSchema} 
          screenId="nav-test" 
          onNavigate={onNavigate}
        />
      );
      
      // Use getAllByRole and click the first one
      const buttons = screen.getAllByRole('button', { name: /navigate button/i });
      await user.click(buttons[0]);
      
      expect(onNavigate).toHaveBeenCalledWith('/dashboard');
    });
  });

  describe('Screen Transitions', () => {
    it('clears form when screenId changes', () => {
      const { rerender } = render(
        <SDUIRenderer schema={mockLoginSchema} screenId="login" />
      );
      
      // Initially renders login form
      expect(screen.getByLabelText(/email/i)).toBeInTheDocument();
      
      // Change to different screen
      rerender(<SDUIRenderer schema={mockDashboardSchema} screenId="dashboard.admin" />);
      
      // Form should be cleared (no email field)
      expect(screen.queryByLabelText(/email/i)).not.toBeInTheDocument();
    });
  });
});

describe('SDUIRenderer Component Behavior', () => {
  it('handles unknown component types gracefully', () => {
    const unknownComponentSchema = {
      id: 'unknown',
      version: '1.0.0',
      metadata: { 
        title: 'Unknown',
        type: 'error' as const,
        auth: 'none' as const,
      },
      layout: {
        type: 'stack' as const,
        components: [
          {
            component: 'UnknownComponent',
            id: 'unknown',
            props: { someProp: 'value' },
          },
        ],
      },
      actions: [],
    } as unknown as UISchema;
    
    render(<SDUIRenderer schema={unknownComponentSchema} screenId="unknown" />);
    
    // Should render the screen title
    expect(screen.getByText('Unknown')).toBeInTheDocument();
    
    // Should show unknown component message
    expect(screen.getByText(/unknown component/i)).toBeInTheDocument();
  });

  it('renders empty grid layout without crashing', () => {
    const emptySchema = {
      id: 'empty',
      version: '1.0.0',
      metadata: { 
        title: 'Empty',
        type: 'list' as const,
        auth: 'none' as const,
      },
      layout: {
        type: 'grid' as const,
        props: { spacing: 2 },
        components: [],
      },
      actions: [],
    } as unknown as UISchema;
    
    render(<SDUIRenderer schema={emptySchema} screenId="empty" />);
    expect(screen.getByText('Empty')).toBeInTheDocument();
  });

  it('handles nested layout children correctly', () => {
    const nestedSchema = {
      id: 'nested',
      version: '1.0.0',
      metadata: { 
        title: 'Nested Layout',
        type: 'detail' as const,
        auth: 'none' as const,
      },
      layout: {
        type: 'root' as const,
        children: [
          {
            type: 'stack' as const,
            children: [
              {
                type: 'flex' as const,
                components: [
                  {
                    component: 'Typography',
                    id: 'nested-text',
                    props: { content: 'Deeply nested text' },
                  },
                ],
              },
            ],
          },
        ],
      },
      actions: [],
    } as unknown as UISchema;
    
    render(<SDUIRenderer schema={nestedSchema} screenId="nested" />);
    expect(screen.getByText('Deeply nested text')).toBeInTheDocument();
  });

  it('renders Alert component correctly', () => {
    const alertSchema = {
      id: 'alert-test',
      version: '1.0.0',
      metadata: { 
        title: 'Alert Test',
        type: 'form' as const,
        auth: 'none' as const,
      },
      layout: {
        type: 'stack' as const,
        components: [
          {
            component: 'Alert',
            id: 'info-alert',
            props: { severity: 'info', content: 'This is an info alert' },
          },
          {
            component: 'Alert',
            id: 'error-alert',
            props: { severity: 'error', content: 'This is an error alert' },
          },
          {
            component: 'Alert',
            id: 'success-alert',
            props: { severity: 'success', content: 'This is a success alert' },
          },
        ],
      },
      actions: [],
    } as unknown as UISchema;
    
    render(<SDUIRenderer schema={alertSchema} screenId="alert-test" />);
    
    expect(screen.getByText('This is an info alert')).toBeInTheDocument();
    expect(screen.getByText('This is an error alert')).toBeInTheDocument();
    expect(screen.getByText('This is a success alert')).toBeInTheDocument();
  });

  it('renders Divider component correctly', () => {
    const dividerSchema = {
      id: 'divider-test',
      version: '1.0.0',
      metadata: { 
        title: 'Divider Test',
        type: 'detail' as const,
        auth: 'none' as const,
      },
      layout: {
        type: 'stack' as const,
        components: [
          {
            component: 'Typography',
            props: { content: 'Above divider' },
          },
          {
            component: 'Divider',
            id: 'test-divider',
            props: { text: 'Divider Text' },
          },
          {
            component: 'Typography',
            props: { content: 'Below divider' },
          },
        ],
      },
      actions: [],
    } as unknown as UISchema;
    
    render(<SDUIRenderer schema={dividerSchema} screenId="divider-test" />);
    
    expect(screen.getByText('Above divider')).toBeInTheDocument();
    expect(screen.getByText('Divider Text')).toBeInTheDocument();
    expect(screen.getByText('Below divider')).toBeInTheDocument();
  });

  it('renders Link component correctly', () => {
    const linkSchema = {
      id: 'link-test',
      version: '1.0.0',
      metadata: { 
        title: 'Link Test',
        type: 'detail' as const,
        auth: 'none' as const,
      },
      layout: {
        type: 'stack' as const,
        components: [
          {
            component: 'Link',
            id: 'test-link',
            props: { href: '/test-path', content: 'Click here' },
          },
        ],
      },
      actions: [],
    } as unknown as UISchema;
    
    render(<SDUIRenderer schema={linkSchema} screenId="link-test" />);
    
    const link = screen.getByText('Click here');
    expect(link).toBeInTheDocument();
    expect(link).toHaveAttribute('href', '/test-path');
  });

  describe('Tabs Component', () => {
    it('renders tabs with string array correctly', () => {
      const tabsSchema = {
        id: 'tabs-test',
        version: '1.0.0',
        metadata: { 
          title: 'Tabs Test',
          type: 'list' as const,
          auth: 'none' as const,
        },
        layout: {
          type: 'stack' as const,
          components: [
            {
              component: 'Tabs',
              id: 'test-tabs',
              props: {
                tabs: ['Overview', 'Details', 'Settings'],
              },
            },
          ],
        },
        actions: [],
      } as unknown as UISchema;
      
      render(<SDUIRenderer schema={tabsSchema} screenId="tabs-test" />);
      
      expect(screen.getByText('Overview')).toBeInTheDocument();
      expect(screen.getByText('Details')).toBeInTheDocument();
      expect(screen.getByText('Settings')).toBeInTheDocument();
    });

    it('renders tabs with object array correctly (fixes [Object, Object] issue)', () => {
      const tabsSchema = {
        id: 'tabs-test-objects',
        version: '1.0.0',
        metadata: { 
          title: 'Tabs Test Objects',
          type: 'list' as const,
          auth: 'none' as const,
        },
        layout: {
          type: 'stack' as const,
          components: [
            {
              component: 'Tabs',
              id: 'test-tabs-objects',
              props: {
                tabs: [
                  { label: 'Overview', value: 'overview' },
                  { label: 'Recent Activity', value: 'activity' },
                  { label: 'Reports', value: 'reports' },
                ],
              },
            },
          ],
        },
        actions: [],
      } as unknown as UISchema;
      
      render(<SDUIRenderer schema={tabsSchema} screenId="tabs-test-objects" />);
      
      // Should show labels, not [Object, Object]
      expect(screen.getByText('Overview')).toBeInTheDocument();
      expect(screen.getByText('Recent Activity')).toBeInTheDocument();
      expect(screen.getByText('Reports')).toBeInTheDocument();
      
      // Should NOT contain [Object, Object]
      expect(screen.queryByText('[Object, Object]')).not.toBeInTheDocument();
    });
  });

  describe('Form Component', () => {
    it('renders Form component without errors', () => {
      const formSchema = {
        id: 'form-test',
        version: '1.0.0',
        metadata: { 
          title: 'Form Test',
          type: 'form' as const,
          auth: 'none' as const,
        },
        layout: {
          type: 'stack' as const,
          components: [
            {
              component: 'Form',
              id: 'test-form',
              props: {
                method: 'POST',
                action: '/api/test',
              },
            },
            {
              component: 'TextField',
              id: 'name',
              props: { name: 'name', label: 'Name', fullWidth: true },
            },
            {
              component: 'Button',
              id: 'submit',
              props: { type: 'submit', variant: 'contained', content: 'Submit' },
            },
          ],
        },
        actions: [],
      } as unknown as UISchema;
      
      render(<SDUIRenderer schema={formSchema} screenId="form-test" />);
      
      // Should not show "Unknown component: Form"
      expect(screen.queryByText('Unknown component: Form')).not.toBeInTheDocument();
      expect(screen.getAllByText('Name').length).toBeGreaterThan(0);
      expect(screen.getByText('Submit')).toBeInTheDocument();
    });

    it('does not render unknown component warning for Form', () => {
      const formSchema = {
        id: 'form-no-warning',
        version: '1.0.0',
        metadata: { 
          title: 'Form No Warning',
          type: 'form' as const,
          auth: 'none' as const,
        },
        layout: {
          type: 'stack' as const,
          components: [
            {
              component: 'Form',
              id: 'test-form',
              props: {},
            },
          ],
        },
        actions: [],
      } as unknown as UISchema;
      
      const { container } = render(<SDUIRenderer schema={formSchema} screenId="form-no-warning" />);
      
      // The Form component should render without showing "Unknown component"
      const unknownWarning = container.querySelector('Unknown component');
      expect(unknownWarning).toBeNull();
    });
  });

  describe('Debug Logging', () => {
    it('logs unknown component types in development', () => {
      const consoleSpy = jest.spyOn(console, 'warn').mockImplementation();
      
      const unknownSchema = {
        id: 'unknown-test',
        version: '1.0.0',
        metadata: { 
          title: 'Unknown Test',
          type: 'detail' as const,
          auth: 'none' as const,
        },
        layout: {
          type: 'stack' as const,
          components: [
            {
              component: 'UnknownComponent',
              id: 'unknown',
              props: {},
            },
          ],
        },
        actions: [],
      } as unknown as UISchema;
      
      render(<SDUIRenderer schema={unknownSchema} screenId="unknown-test" />);
      
      expect(consoleSpy).toHaveBeenCalledWith(
        expect.stringContaining('[SDUI] Unknown component:'),
        expect.any(Object)
      );
      
      consoleSpy.mockRestore();
    });
  });

  describe('Chart Components (Parity with Original Dashboard)', () => {
    it('renders LineChart component correctly', () => {
      const chartSchema = {
        id: 'chart-test',
        version: '1.0.0',
        metadata: { 
          title: 'Chart Test',
          type: 'dashboard' as const,
          auth: 'none' as const,
        },
        layout: {
          type: 'stack' as const,
          components: [
            {
              component: 'LineChart',
              id: 'revenue-chart',
              props: {
                title: 'Revenue Trend',
                data: {
                  labels: ['Jan', 'Feb', 'Mar'],
                  datasets: [{
                    label: 'Revenue',
                    data: [100, 200, 300],
                    borderColor: '#1976d2',
                    backgroundColor: 'rgba(25, 118, 210, 0.1)',
                  }],
                },
                height: 240,
              },
            },
          ],
        },
        actions: [],
      } as unknown as UISchema;
      
      render(<SDUIRenderer schema={chartSchema} screenId="chart-test" />);
      
      expect(screen.getByText('Revenue Trend')).toBeInTheDocument();
    });

    it('renders DoughnutChart component correctly', () => {
      const chartSchema = {
        id: 'doughnut-test',
        version: '1.0.0',
        metadata: { 
          title: 'Doughnut Test',
          type: 'dashboard' as const,
          auth: 'none' as const,
        },
        layout: {
          type: 'stack' as const,
          components: [
            {
              component: 'DoughnutChart',
              id: 'status-chart',
              props: {
                title: 'Status Breakdown',
                data: {
                  labels: ['Active', 'Pending', 'Failed'],
                  datasets: [{
                    label: 'Status',
                    data: [10, 5, 2],
                    backgroundColor: ['#4caf50', '#ff9800', '#f44336'],
                  }],
                },
                height: 240,
              },
            },
          ],
        },
        actions: [],
      } as unknown as UISchema;
      
      render(<SDUIRenderer schema={chartSchema} screenId="doughnut-test" />);
      
      expect(screen.getByText('Status Breakdown')).toBeInTheDocument();
    });

    it('renders KPIGrid component correctly', () => {
      const kpiSchema = {
        id: 'kpi-test',
        version: '1.0.0',
        metadata: { 
          title: 'KPI Test',
          type: 'dashboard' as const,
          auth: 'none' as const,
        },
        layout: {
          type: 'stack' as const,
          components: [
            {
              component: 'KPIGrid',
              id: 'metrics-grid',
              props: {
                columns: 4,
                items: [
                  { title: 'Total Orders', value: '1,234', loading: false },
                  { title: 'Total Deliveries', value: '987', loading: false },
                  { title: 'Total Revenue', value: 'KES 245,000', loading: false },
                  { title: 'Active Riders', value: '45', loading: false },
                ],
              },
            },
          ],
        },
        actions: [],
      } as unknown as UISchema;
      
      render(<SDUIRenderer schema={kpiSchema} screenId="kpi-test" />);
      
      expect(screen.getByText('Total Orders')).toBeInTheDocument();
      expect(screen.getByText('Total Deliveries')).toBeInTheDocument();
      expect(screen.getByText('Total Revenue')).toBeInTheDocument();
      expect(screen.getByText('Active Riders')).toBeInTheDocument();
    });
  });

  describe('SDUI Parity Verification', () => {
    it('can render admin dashboard schema with all component types', () => {
      // This test verifies parity with the original AdminDashboard.tsx
      const adminDashboardSchema = {
        id: 'dashboard.admin',
        version: '1.0.0',
        metadata: { 
          title: 'Admin Dashboard',
          type: 'dashboard' as const,
          auth: 'required' as const,
        },
        layout: {
          type: 'grid' as const,
          props: { columns: 12, spacing: 3 },
          components: [
            // Metric Cards (like KPIGrid in original)
            {
              component: 'MetricCard',
              id: 'total-orders',
              props: { label: 'Total Orders', value: '1,234', trend: 'up', change: '+12%' },
            },
            {
              component: 'MetricCard',
              id: 'total-deliveries',
              props: { label: 'Total Deliveries', value: '987', trend: 'up', change: '+8%' },
            },
            {
              component: 'MetricCard',
              id: 'total-revenue',
              props: { label: 'Total Revenue', value: 'KES 245,000', trend: 'up', change: '+15%' },
            },
            {
              component: 'MetricCard',
              id: 'active-riders',
              props: { label: 'Active Riders', value: '45', trend: 'down', change: '-3%' },
            },
            // Charts
            {
              component: 'LineChart',
              id: 'revenue-chart',
              props: {
                title: 'Revenue Trend',
                data: {
                  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul'],
                  datasets: [{
                    label: 'Revenue (KES)',
                    data: [125000, 145000, 138000, 172000, 189000, 210000, 245000],
                    borderColor: '#1976d2',
                    backgroundColor: 'rgba(25, 118, 210, 0.1)',
                  }],
                },
                height: 240,
              },
            },
            {
              component: 'DoughnutChart',
              id: 'settlement-chart',
              props: {
                title: 'Settlement Status',
                data: {
                  labels: ['Completed', 'Processing', 'Pending', 'Failed'],
                  datasets: [{
                    label: 'Settlements',
                    data: [145, 32, 18, 5],
                    backgroundColor: ['#4caf50', '#2196f3', '#ff9800', '#f44336'],
                  }],
                },
                height: 240,
              },
            },
            // Tabs
            {
              component: 'Tabs',
              id: 'dashboard-tabs',
              props: {
                tabs: [
                  { label: 'Overview', value: 'overview' },
                  { label: 'Recent Activity', value: 'activity' },
                  { label: 'Reports', value: 'reports' },
                ],
              },
            },
            // Data Table
            {
              component: 'DataTable',
              id: 'activity-table',
              props: {
                columns: [
                  { key: 'id', label: 'ID' },
                  { key: 'message', label: 'Activity' },
                  { key: 'timestamp', label: 'Time' },
                ],
                rows: [
                  { id: '1', message: 'Delivery #1001 completed', timestamp: '2024-01-15 10:30' },
                  { id: '2', message: 'New booking #1002 received', timestamp: '2024-01-15 09:15' },
                  { id: '3', message: 'Driver assigned to #1001', timestamp: '2024-01-15 08:00' },
                ],
              },
            },
          ],
        },
        actions: [
          { id: 'refresh', type: 'api' as const, label: 'Refresh', endpoint: '/api/dashboard/refresh', method: 'POST' },
        ],
      } as unknown as UISchema;
      
      render(<SDUIRenderer schema={adminDashboardSchema} screenId="dashboard.admin" />);
      
      // Verify all major components render
      expect(screen.getByText('Total Orders')).toBeInTheDocument();
      expect(screen.getByText('Total Deliveries')).toBeInTheDocument();
      expect(screen.getByText('Total Revenue')).toBeInTheDocument();
      expect(screen.getByText('Active Riders')).toBeInTheDocument();
      expect(screen.getByText('Revenue Trend')).toBeInTheDocument();
      expect(screen.getByText('Settlement Status')).toBeInTheDocument();
      expect(screen.getByText('Overview')).toBeInTheDocument();
      expect(screen.getByText('Recent Activity')).toBeInTheDocument();
      expect(screen.getByText('Reports')).toBeInTheDocument();
      expect(screen.getByText('ID')).toBeInTheDocument();
      expect(screen.getByText('Activity')).toBeInTheDocument();
      expect(screen.getByText('Time')).toBeInTheDocument();
    });
  });

  describe('Layout Primitives Verification', () => {
    it('renders grid layout with proper structure', () => {
      const gridSchema = {
        id: 'grid-test',
        version: '1.0.0',
        metadata: { 
          title: 'Grid Test',
          type: 'dashboard' as const,
          auth: 'none' as const,
        },
        layout: {
          type: 'grid' as const,
          props: { columns: 12, spacing: 3 },
          components: [
            {
              component: 'Typography',
              id: 'item1',
              props: { content: 'Grid Item 1' },
            },
            {
              component: 'Typography',
              id: 'item2',
              props: { content: 'Grid Item 2' },
            },
          ],
        },
        actions: [],
      } as unknown as UISchema;
      
      const { container } = render(<SDUIRenderer schema={gridSchema} screenId="grid-test" />);
      
      // Verify grid container exists
      expect(container.querySelector('.MuiGrid-container')).toBeInTheDocument();
    });

    it('renders flex layout with proper structure', () => {
      const flexSchema = {
        id: 'flex-test',
        version: '1.0.0',
        metadata: { 
          title: 'Flex Test',
          type: 'dashboard' as const,
          auth: 'none' as const,
        },
        layout: {
          type: 'flex' as const,
          props: { spacing: 2, direction: 'row' },
          components: [
            {
              component: 'Typography',
              id: 'item1',
              props: { content: 'Flex Item 1' },
            },
            {
              component: 'Typography',
              id: 'item2',
              props: { content: 'Flex Item 2' },
            },
          ],
        },
        actions: [],
      } as unknown as UISchema;
      
      render(<SDUIRenderer schema={flexSchema} screenId="flex-test" />);
      
      expect(screen.getByText('Flex Item 1')).toBeInTheDocument();
      expect(screen.getByText('Flex Item 2')).toBeInTheDocument();
    });

    it('renders nested layout structure (grid > flex > components)', () => {
      const nestedSchema = {
        id: 'nested-test',
        version: '1.0.0',
        metadata: { 
          title: 'Nested Test',
          type: 'dashboard' as const,
          auth: 'none' as const,
        },
        layout: {
          type: 'grid' as const,
          props: { columns: 12, spacing: 3 },
          children: [
            {
              type: 'flex' as const,
              props: { gridColumn: 'span 8', spacing: 2 },
              components: [
                {
                  component: 'Typography',
                  id: 'main-content',
                  props: { content: 'Main Content' },
                },
              ],
            },
            {
              type: 'flex' as const,
              props: { gridColumn: 'span 4', spacing: 2 },
              components: [
                {
                  component: 'Typography',
                  id: 'sidebar',
                  props: { content: 'Sidebar' },
                },
              ],
            },
          ],
        },
        actions: [],
      } as unknown as UISchema;
      
      render(<SDUIRenderer schema={nestedSchema} screenId="nested-test" />);
      
      expect(screen.getByText('Main Content')).toBeInTheDocument();
      expect(screen.getByText('Sidebar')).toBeInTheDocument();
    });

    it('renders stack layout with proper vertical spacing', () => {
      const stackSchema = {
        id: 'stack-test',
        version: '1.0.0',
        metadata: { 
          title: 'Stack Test',
          type: 'detail' as const,
          auth: 'none' as const,
        },
        layout: {
          type: 'stack' as const,
          props: { spacing: 3, maxWidth: 400 },
          components: [
            {
              component: 'Typography',
              id: 'title',
              props: { content: 'Title', variant: 'h4' },
            },
            {
              component: 'Typography',
              id: 'description',
              props: { content: 'Description text here' },
            },
            {
              component: 'Button',
              id: 'action',
              props: { content: 'Click Me', variant: 'contained' },
            },
          ],
        },
        actions: [],
      } as unknown as UISchema;
      
      render(<SDUIRenderer schema={stackSchema} screenId="stack-test" />);
      
      expect(screen.getByText('Title')).toBeInTheDocument();
      expect(screen.getByText('Description text here')).toBeInTheDocument();
      expect(screen.getByText('Click Me')).toBeInTheDocument();
    });
  });

  describe('Movers Homepage Rendering', () => {
    it('renders movers homepage with hero section', () => {
      render(<SDUIRenderer schema={mockMoversHomeSchema} screenId="movers-home" />);
      
      // Check hero section is rendered (template variables are resolved)
      // There are multiple instances of these texts (header + hero), so use getAllByText
      expect(screen.getAllByText('ZanaFleet Movers').length).toBeGreaterThan(0);
      expect(screen.getAllByText('Reliable Moving Services').length).toBeGreaterThan(0);
    });

    it('renders services section with all service cards', () => {
      render(<SDUIRenderer schema={mockMoversHomeSchema} screenId="movers-home" />);
      
      // Check services title
      expect(screen.getByText('Our Services')).toBeInTheDocument();
      
      // Check service cards
      expect(screen.getByText('Residential Moving')).toBeInTheDocument();
      expect(screen.getByText('Commercial Moving')).toBeInTheDocument();
      expect(screen.getByText('Packing Services')).toBeInTheDocument();
      expect(screen.getByText('Storage Solutions')).toBeInTheDocument();
    });

    it('renders CTA section with contact info', () => {
      render(<SDUIRenderer schema={mockMoversHomeSchema} screenId="movers-home" />);
      
      // Check CTA title
      expect(screen.getByText('Ready to Move?')).toBeInTheDocument();
      
      // Check contact info (with template variable)
      expect(screen.getByText(/Contact us for a free quote today/)).toBeInTheDocument();
    });

    it('has correct metadata for movers homepage', () => {
      expect(mockMoversHomeSchema.screenId).toBe('movers-home');
      expect(mockMoversHomeSchema.version).toBe('1.0.0');
      expect(mockMoversHomeSchema.metadata.title).toBe('ZanaFleet Movers');
      expect(mockMoversHomeSchema.metadata.type).toBe('movers-home');
      expect(mockMoversHomeSchema.metadata.auth).toBe('none');
      expect(mockMoversHomeSchema.metadata.cacheDuration).toBe(300);
    });

    it('has correct data sources configuration', () => {
      const configSource = mockMoversHomeSchema.data?.find(d => d.id === 'config');
      expect(configSource).toBeDefined();
      expect(configSource?.type).toBe('static');
      expect(configSource?.staticData).toHaveProperty('companyName', 'ZanaFleet Movers');
      expect(configSource?.staticData).toHaveProperty('ctaText', 'Get a Free Quote');
      expect(configSource?.staticData).toHaveProperty('phoneNumber');
      expect(configSource?.staticData).toHaveProperty('email');
    });

    it('has correct layout structure', () => {
      expect(mockMoversHomeSchema.layout.type).toBe('flex');
      expect(mockMoversHomeSchema.layout.children).toBeDefined();
      expect(mockMoversHomeSchema.layout.children?.length).toBe(3); // Hero, Services, CTA
    });

    it('has navigation actions defined', () => {
      expect(mockMoversHomeSchema.actions).toBeDefined();
      expect(mockMoversHomeSchema.actions.length).toBe(2);
      
      const quoteAction = mockMoversHomeSchema.actions.find(a => a.id === 'open-quote-form');
      expect(quoteAction).toBeDefined();
      expect(quoteAction?.type).toBe('navigate');
      expect(quoteAction?.navigateTo).toBe('quote');
      
      const loginAction = mockMoversHomeSchema.actions.find(a => a.id === 'navigate-to-login');
      expect(loginAction).toBeDefined();
      expect(loginAction?.type).toBe('navigate');
      expect(loginAction?.navigateTo).toBe('login');
    });

    it('matches expected schema from API', () => {
      // This test ensures the schema matches what the API generates
      // by verifying all required properties are present
      expect(mockMoversHomeSchema.screenId).toBeDefined();
      expect(mockMoversHomeSchema.version).toBeDefined();
      expect(mockMoversHomeSchema.metadata).toBeDefined();
      expect(mockMoversHomeSchema.data).toBeDefined();
      expect(mockMoversHomeSchema.layout).toBeDefined();
      expect(mockMoversHomeSchema.actions).toBeDefined();
      
      // Verify no validation rules (not needed for public page)
      expect(mockMoversHomeSchema.validations).toBeUndefined();
    });
  });
});
